+ api test fix

diff --git a/.github/workflows/run-api-tests.yml b/.github/workflows/run-api-tests.yml
--- a/.github/workflows/run-api-tests.yml
+++ b/.github/workflows/run-api-tests.yml
@@ -4,11 +4,15 @@ on:
     branches: [ "main" ]
   pull_request:
     branches: [ "main" ]
+
 permissions: 
-  contents: write
+  contents: read
+  actions: read
+  checks: write
   issues: write 
   pull-requests: write 
   statuses: write
+
 jobs:
   run-api-tests:
     name: Run API Tests
@@ -24,14 +28,6 @@ jobs:
       - name: Checkout code
         uses: actions/checkout@v4
 
-      # Authenticate using GitHub App 
-      - name: Authenticate GitHub App 
-        run: | 
-          echo "${{ secrets.GITHUB_APP_PRIVATE_KEY }}" > private-key.pem 
-          export GITHUB_APP_ID=1068219 
-          export GITHUB_INSTALLATION_ID=57554126  
-          export GITHUB_PRIVATE_KEY=$(cat private-key.pem) 
-          echo "GitHub App authenticated"
       
       # Restore .NET dependencies
       - name: Restore dependencies
@@ -57,23 +53,14 @@ jobs:
     runs-on: ubuntu-latest
     needs: run-api-tests
     steps:
-      # Authenticate using GitHub App 
-      - name: Authenticate GitHub App 
-        run: | 
-          echo "${{ secrets.GITHUB_APP_PRIVATE_KEY }}" > private-key.pem 
-          export GITHUB_APP_ID=${{ secrets.GITHUB_APP_ID }} 
-          export GITHUB_INSTALLATION_ID=${{ secrets.GITHUB_INSTALLATION_ID }} 
-          export GITHUB_PRIVATE_KEY=$(cat private-key.pem) 
-          echo "GitHub App authenticated"
-      
+            
       # Display test results using dorny/test-reporter
-      - name: Publish Test Report
-        uses: dorny/test-reporter@v1
-        if: always() # Always run this step, even if previous steps fail
+      - name: Test Reporter
+        uses: dorny/test-reporter@v1.9.1
+        if: success() || failure()  # Always run this step, even if previous steps fail
         with:
           artifact: test-results
           name: api tests results
           path: './test-results.trx'
           reporter: dotnet-trx
           fail-on-error: false
-          token: ${{ secrets.GITHUB_APP_PRIVATE_KEY}}
